env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.10" BUILD_DOCS=0
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.11" BUILD_DOCS=1
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.10" BUILD_DOCS=0
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.11" BUILD_DOCS=0
  - TRAVIS_PYTHON_VERSION="3.5" NUMPY_VERSION="1.10" BUILD_DOCS=0
  - TRAVIS_PYTHON_VERSION="3.5" NUMPY_VERSION="1.11" BUILD_DOCS=0
  global:
    - secure: UxPkdFKl0xtk+H+98CNHSnYN8SJrEq5xJjLtPUPR+5UF5lLKL7godwrOdYeO0B0fXPi2Plw0vtoIID6H1AV4x+8QD/AgAizoWIh8KLim3E7rDX0v0M3WnUHctvYwt76mGCYvIGH6qR2Ziml37Ec6nz2aTuz0oex27P6dq0BKkXs=
    - secure: OFyhYR18rMC/MlyG1J8+cRkHWlkn/BOkQP6IM+ZBILG/t33ipoyTjH2qpNJi5Rx3wMCXBn00XnPExf7mqRBAAzSULyt6t6eDbXgInYOCSOQMMZlJ66CdmsD8dKBwDVbcFuGz06amYrIc/22guFP+6GfhsCepHvocrR93A93whug=
os:
- linux
- osx
sudo: false
install:
- echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION, $TRAVIS_TAG"
- if [[ "$TRAVIS_TAG" == v* ]]; then echo "This is a release."; export BUILD_STR=""; else echo "This is not a release."; export BUILD_STR="dev"; fi
- bash .ci/travis/install_python.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- pip install coveralls
- conda build -q .conda-recipe --numpy=$NUMPY_VERSION
- conda install -q landlab --use-local
script:
- if [[ "$BUILD_DOCS" == "1" ]]; then (cd docs && make html 2> /dev/null); fi
- bash .ci/travis/run_travis_test.sh
virtualenv:
  system_site_packages: false
after_success:
  - bash .ci/travis/deploy_to_pypi.sh
  - bash .ci/travis/deploy_to_anaconda.sh
  - coveralls
deploy:
  provider: pypi
  user: mcflugen
  password:
    secure: V15DceMv4DUmjgxToaxrP3KaQxsLbfrTkB1s6D8YNQZvYJiVvNlBpC1nF8yWbOt3IWJQSGjaQEnObd2ZhHe2Kq/H+QsEFyBKlYF7SNp35FyS5zLuf2qhnNhmzhqkspwBpiGe88c1PQPFzfqdIUQXp7ZAv6L8YRvNy2sbzvgxh6I=
  on:
    tags: true
    branch: release
    repo: landlab/landlab
  distributions: sdist bdist_wheel
notifications:
  slack:
    secure: gRKbqjPgp0ZcFtecHOwjLAFbzzBr2zyFrxk7OAS/cea/9U8bLQNA0jZs3ZHtAgR53gdnFlx/GI10d/KD9XMKU55gQkO4FSvfYMK7Xzs2tfnEa5flTqQKRfjB1oJ2fmb81yshUe+xKsXBoedP7SPYv2mutMOY8srKwUcuE0yGmAw=
