package:
  name: landlab
  version: "1.0.0"

source:
  path: ..

requirements:
  build:
    - python
    - libgcc # [linux and py27 and np == '19']
    - scipy
    - numpy x.x
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - cython
    - six
    - pyyaml
    - setuptools

  run:
    - python
    - libgcc # [linux and py27 and np == '19']
    - scipy
    - numpy x.x
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - cython
    - six
    - pyyaml
    - setuptools

build:
  string: {{ environ.get('BUILD_STR', '') }}
